Upgrade DLL build to .NET 5
KSP-CKAN/CKAN pull request #3194
Opened 2020-11-12 00:09 UTC by DasSkelett

## Motivation
Mostly because I already have the changes and because @HebaruSan said I should do a PR :D
Also [.NET 5 has been released yesterday](https://devblogs.microsoft.com/dotnet/announcing-net-5-0/) as "the first release in [Microsoft's] .NET unification journey."

The Core DLL isn't really used anywhere on its own, especially in its .NET (Core) form, so this shouldn't break anything either.

One day we want to create a new GUI based on MAUI, so it's not a bad idea to keep the Core up to date.

## Changes
* Changed the `netstandard2.0` `TargetFramework` to `net5.0` in `CKAN-core.csproj`. The `net45` one is untouched.
* Changed the `netcoreapp3.1` `TargetFramework` to `net5.0` in `Tests.csproj`. The `net45` one is untouched.
* Put our own `IEnumerable.TohashSet()` implementation between `#if NET45 ... #endif`, since .NET 5 (and even .NET Framework 4.7.2) comes with a native implementation. We'll have to update this if/when we ever change our Framework build away from 4.5.
* Related, changed a line in the test that called `TohashSet()` via the full namespace path as static funtion, passing the object, to calling it on the object.
* Upgraded Cake to v0.38.5 which has improved .NET 5 support. I've also just seen that there is Cake v1.0.0-rc1 available now, but I haven't tested it yet.
* Upgraded the cake build script to target `net5.0` for .NET (Core) builds.
* And changed our GitHub workflow to install .NET 5 prior to running our netcore build script.

2020-11-13 01:30 UTC, HebaruSan commented on Core/Configuration/JsonConfiguration.cs
>                      // If we are not running on .NET Standard, try to migrate from the real registry
Should this comment about .NET Standard be updated now that the condition is no longer `!NETSTANDARD`?

2020-11-13 01:33 UTC, HebaruSan requested changes
There are a bunch of warnings like this in the PR's code listing:

![image](https://user-images.githubusercontent.com/1559108/99017634-f7680200-251d-11eb-8852-9e1ecb4c04ea.png)

I guess they have a point. We could just not catch those exceptions.

2020-11-22 00:15 UTC, DasSkelett commented
> There are a bunch of warnings like this in the PR's code listing:
> 
> I guess they have a point. We could just not catch those exceptions.

Removed the try-catch blocks, and instead moved the explaining messages into proper code documentation. There's only this one left, something something Code Access Security. I don't really know that, so I have to do some reading to find out what it's for and how to migrate that to .NET Core.

2020-11-22 05:32 UTC, HebaruSan commented
I would say nuke it, but the FileSystemWatcher documentation still mentions it:

- https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=net-5.0

> This class contains a link demand and an inheritance demand at the class level that applies to all members. A SecurityException is thrown when either the immediate caller or the derived class does not have full-trust permission. For details about security demands, see Link Demands.

I don't want to have to deal with SecurityExceptions unexpectedly. Let's leave this as-is; hopefully, if it runs on a runtime that supports CAS it will work OK, and if it runs on a runtime that doesn't support CAS no exception will be thrown regardless.

2020-11-22 05:33 UTC, HebaruSan approved these changes
:canoe:

2020-11-22 05:36 UTC, merged